-- 1) TABLES
create table staff (
  id text primary key,
  nama text not null,
  jawatan text not null,
  pin text default '1234',
  img text
);

create table kehadiran (
  id bigint generated by default as identity primary key,
  staff_id text,
  nama text,
  jawatan text,
  tarikh text,
  masa_in text,
  masa_out text,
  open boolean default true,
  kaedah text,
  gps text,
  status_out text,
  waktu text,
  ts bigint unique
);

create table tetapan (
  id int primary key default 1,
  data jsonb not null default '{}'
);

-- 2) DATA AWAL TETAPAN
insert into tetapan (id, data) values (1, '{"lat":3.139,"lng":101.687,"radius":150,"durasiSolat":30,"kadarImam":15,"kadarBilal":10,"zon":"SGR01","pin":"1234","namaMasjid":"Masjid Attendance Pro","alamat":"","logoMasjid":null}')
on conflict (id) do nothing;

-- 3) RLS (terbuka untuk kegunaan dalaman; tambah Supabase Auth untuk production)
alter table staff enable row level security;
alter table kehadiran enable row level security;
alter table tetapan enable row level security;
create policy "staff_all" on staff for all using (true) with check (true);
create policy "kehadiran_all" on kehadiran for all using (true) with check (true);
create policy "tetapan_all" on tetapan for all using (true) with check (true);

-- 4) REALTIME (sync masa-nyata antara peranti)
alter publication supabase_realtime add table staff, kehadiran, tetapan;